Implement `Functors.functor`
TuringLang/Bijectors.jl pull request #162
Opened 2021-01-10 14:33 UTC by devmotion

This PR is an alternative to https://github.com/TuringLang/Bijectors.jl/pull/161. As mentioned there, `Flux.@treelike` does not exist anymore. Instead, Flux relies on `Functors.functor` and reexports `Flux.@functor`.

This PR implements `Functors.functor` for bijectors and normalizing flows. Thus users can just call `Flux.params` without implementing `@functor` for the different layers.

A dependency on the lightweight package Functors.jl is added and the optional dependency on Flux is dropped.

2021-01-10 16:33 UTC, torfjelde requested changes
This is great stuff!
I have one comment about the testing; it seems like we currently only test a couple of the bijectors?

2021-01-10 16:33 UTC, torfjelde commented on test/bijectors/utils.jl
> +end
Is this being used anywhere?

2021-01-10 17:29 UTC, devmotion commented on test/bijectors/utils.jl
> +end
Yes, in the `norm_flows` tests.

2021-01-10 17:33 UTC, devmotion commented
Yes, indeed, so far only `InvertibleBatchnorm`, `PlanarLayer`, and `RadialLayer` are tested in `norm_flows.jl`. I am still a bit confused about the test setup - where would be the best place to add tests for other bijectors? Initially I assume that most interface tests would be handled by `test_bijector` but it seems it is only used in one single test?

2021-01-10 18:59 UTC, torfjelde commented
> where would be the best place to add tests for other bijectors? Initially I assume that most interface tests would be handled by test_bijector but it seems it is only used in one single test?

That's correct, but the idea is to start using that approach for all bijectors. So feel free to add it there for now :)

2021-01-10 19:00 UTC, torfjelde commented on test/bijectors/utils.jl
> +end
Ah, missed that :+1:

2021-01-10 19:01 UTC, torfjelde commented
Actually, I guess it's somewhat non-trivial to add this to `test_bijector`, as we don't have access to the parameters of the bijector itself?

2021-01-11 17:41 UTC, devmotion commented
I assume one would have to specify the parameters explicitly, similar to `test_functor`. However, one could set to `nothing` by default and skip the tests in this case.

2021-01-11 18:22 UTC, devmotion commented
This will lead to a stackoverflow error. But in principle this is the idea.

2021-01-11 18:25 UTC, torfjelde commented
Oh yeah, rather:

``` julia
function test_bijector(
    b::Bijector,
    xs_true,
    ys_true,
    logjacs_true
    params;
    kwargs...
)
    test_functor(b, params)
    return test_bijector(b, xs_true, ys_true, logjacs_true; kwargs...)
end
```

2021-01-16 07:41 UTC, torfjelde approved these changes
I'm happy for now, and we can make it testing the functor functionality part of the tests once we unify testing a bit.

2021-01-16 10:42 UTC, devmotion commented
Ah sorry, I forgot about the PR. OK, let's update the tests separately then!

2021-01-16 10:42 UTC, merged